"""hi

Revision ID: 248daf8cc8e9
Revises: 678a5453c98b
Create Date: 2019-06-26 11:23:56.614831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '248daf8cc8e9'
down_revision = '678a5453c98b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channelname', sa.String(length=64), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_channelname'), 'channel', ['channelname'], unique=True)
    op.create_table('channel_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_messages_timestamp'), 'channel_messages', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channel_messages_timestamp'), table_name='channel_messages')
    op.drop_table('channel_messages')
    op.drop_index(op.f('ix_channel_channelname'), table_name='channel')
    op.drop_table('channel')
    # ### end Alembic commands ###
