"""channel table

Revision ID: 678a5453c98b
Revises: 6efc50572a1c
Create Date: 2019-06-25 15:51:37.566522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '678a5453c98b'
down_revision = '6efc50572a1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channelmembers',
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('channelmembers')
    # ### end Alembic commands ###
