"""empty message

Revision ID: ccb12e3023ff
Revises: 248daf8cc8e9
Create Date: 2019-07-04 15:13:09.812752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccb12e3023ff'
down_revision = '248daf8cc8e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('channel_admin_id_fkey', 'channel', type_='foreignkey')
    op.create_foreign_key(None, 'channel', 'user', ['admin_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('channel_messages_channel_id_fkey', 'channel_messages', type_='foreignkey')
    op.drop_constraint('channel_messages_sender_id_fkey', 'channel_messages', type_='foreignkey')
    op.create_foreign_key(None, 'channel_messages', 'channel', ['channel_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'channel_messages', 'user', ['sender_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.VARCHAR(length=140), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'channel_messages', type_='foreignkey')
    op.drop_constraint(None, 'channel_messages', type_='foreignkey')
    op.create_foreign_key('channel_messages_sender_id_fkey', 'channel_messages', 'user', ['sender_id'], ['id'])
    op.create_foreign_key('channel_messages_channel_id_fkey', 'channel_messages', 'channel', ['channel_id'], ['id'])
    op.drop_constraint(None, 'channel', type_='foreignkey')
    op.create_foreign_key('channel_admin_id_fkey', 'channel', 'user', ['admin_id'], ['id'])
    # ### end Alembic commands ###
