"""channel table

Revision ID: ee06412d8b86
Revises: 1af05aedf662
Create Date: 2019-06-25 10:52:12.719599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee06412d8b86'
down_revision = '1af05aedf662'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.drop_constraint('channel_user_id_fkey', 'channel', type_='foreignkey')
    op.create_foreign_key(None, 'channel', 'user', ['admin_id'], ['id'])
    op.drop_column('channel', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'channel', type_='foreignkey')
    op.create_foreign_key('channel_user_id_fkey', 'channel', 'user', ['user_id'], ['id'])
    op.drop_column('channel', 'admin_id')
    # ### end Alembic commands ###
